export const FETCH_TASK = "FETCH_TASK";

export const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS";

export const FETCH_TASK_ERROR = "FETCH_TASK_ERROR";

export const FILTER_TASK = "FILTER_TASK";

export const FILTER_TASK_SUCCESS = "FILTER_TASK_SUCCESS";

export const ADD_TASK = "ADD_TASK";

export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";

export const ADD_TASK_ERROR = "ADD_TASK_ERROR";

export const SET_TASK_EDITING = "SET_TASK_EDITING";

export const EDIT_TASK = "EDIT_TASK"

export const EDIT_TASK_SUCCESS = "EDIT_TASK_SUCCESS";

export const EDIT_TASK_ERROR = "EDIT_TASK_ERROR";


export const DELETE_TASK = "DELETE_TASK"

export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";

export const DELETE_TASK_ERROR = "DELETE_TASK_ERROR";
